### PR TITLE
Refactor and fix epipe error

### PR DESCRIPTION
**Pull request by diclophis**
@cantino / @juanca please review. this should fix the `EPIPE` errors

### CODE REVIEW

**Comment by cantino** [comment]
Where were the primary changes?

**Comment by diclophis** [comment]
@cantino the gist of the fix is that we moved the connection into the `Context` instead of it being in the `Runtime` ... the theory is that rails creates 1 runtime, that is then shared with each unicorn worker process ... this of course could totally break if one unicorn process was using the connection, and another one tried to "hijack" it... This was amplified because on `javascript error` the library would "ensure_shutdown" of the nodejs server ... so if 1 unicorn worker was processing an invalid coffescript file, and began to shutdown the server, while another unicorn worker process was still trying to pipe things to it... boom EPIPE.

As it currently has been written, we moved the connection and nodejs bootup into the Context, this ensure that each unicorn worker gets its own connection and nodejs process ... per context, but in practice it also appears that there are multiple contents initialized (in our local test we have already seen more than 5 created just loading the dashboard).

So I think we are going to do one more refactor that starts the nodejs server with the Runtime... but each context opens its own connection to that server.

**Comment by juanca** [comment]
I'll checkout this branch and see if I can reproduce my `EPIPE`s

**Comment by juanca** [comment]
I can't reproduce my broken pipes :dancers:

**Pull request merged**
